package com.bmw.mapper;

import com.bmw.entity.Materials;
import com.bmw.entity.MaterialsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MaterialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    long countByExample(MaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    int deleteByExample(MaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    int deleteByPrimaryKey(String materialsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    int insert(Materials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    int insertSelective(Materials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    List<Materials> selectByExample(MaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    Materials selectByPrimaryKey(String materialsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") Materials record, @Param("example") MaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    int updateByExample(@Param("record") Materials record, @Param("example") MaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    int updateByPrimaryKeySelective(Materials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    int updateByPrimaryKey(Materials record);
}