package com.bmw.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.bmw.dto.OrderDTO;
import com.bmw.entity.Order;
import com.bmw.entity.OrderExample;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    Order selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    int updateByPrimaryKey(Order record);

    List<OrderDTO> getUnconfirmedOrderList(Map paramMap);
}