package com.bmw.entity;

import java.util.ArrayList;
import java.util.List;

public class MaterialsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public MaterialsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMaterialsidIsNull() {
            addCriterion("materialsId is null");
            return (Criteria) this;
        }

        public Criteria andMaterialsidIsNotNull() {
            addCriterion("materialsId is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialsidEqualTo(String value) {
            addCriterion("materialsId =", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidNotEqualTo(String value) {
            addCriterion("materialsId <>", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidGreaterThan(String value) {
            addCriterion("materialsId >", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidGreaterThanOrEqualTo(String value) {
            addCriterion("materialsId >=", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidLessThan(String value) {
            addCriterion("materialsId <", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidLessThanOrEqualTo(String value) {
            addCriterion("materialsId <=", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidLike(String value) {
            addCriterion("materialsId like", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidNotLike(String value) {
            addCriterion("materialsId not like", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidIn(List<String> values) {
            addCriterion("materialsId in", values, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidNotIn(List<String> values) {
            addCriterion("materialsId not in", values, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidBetween(String value1, String value2) {
            addCriterion("materialsId between", value1, value2, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidNotBetween(String value1, String value2) {
            addCriterion("materialsId not between", value1, value2, "materialsid");
            return (Criteria) this;
        }

        public Criteria andCartypeIsNull() {
            addCriterion("carType is null");
            return (Criteria) this;
        }

        public Criteria andCartypeIsNotNull() {
            addCriterion("carType is not null");
            return (Criteria) this;
        }

        public Criteria andCartypeEqualTo(String value) {
            addCriterion("carType =", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotEqualTo(String value) {
            addCriterion("carType <>", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeGreaterThan(String value) {
            addCriterion("carType >", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeGreaterThanOrEqualTo(String value) {
            addCriterion("carType >=", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLessThan(String value) {
            addCriterion("carType <", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLessThanOrEqualTo(String value) {
            addCriterion("carType <=", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLike(String value) {
            addCriterion("carType like", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotLike(String value) {
            addCriterion("carType not like", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeIn(List<String> values) {
            addCriterion("carType in", values, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotIn(List<String> values) {
            addCriterion("carType not in", values, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeBetween(String value1, String value2) {
            addCriterion("carType between", value1, value2, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotBetween(String value1, String value2) {
            addCriterion("carType not between", value1, value2, "cartype");
            return (Criteria) this;
        }

        public Criteria andModelcodeIsNull() {
            addCriterion("modelCode is null");
            return (Criteria) this;
        }

        public Criteria andModelcodeIsNotNull() {
            addCriterion("modelCode is not null");
            return (Criteria) this;
        }

        public Criteria andModelcodeEqualTo(String value) {
            addCriterion("modelCode =", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeNotEqualTo(String value) {
            addCriterion("modelCode <>", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeGreaterThan(String value) {
            addCriterion("modelCode >", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeGreaterThanOrEqualTo(String value) {
            addCriterion("modelCode >=", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeLessThan(String value) {
            addCriterion("modelCode <", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeLessThanOrEqualTo(String value) {
            addCriterion("modelCode <=", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeLike(String value) {
            addCriterion("modelCode like", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeNotLike(String value) {
            addCriterion("modelCode not like", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeIn(List<String> values) {
            addCriterion("modelCode in", values, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeNotIn(List<String> values) {
            addCriterion("modelCode not in", values, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeBetween(String value1, String value2) {
            addCriterion("modelCode between", value1, value2, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeNotBetween(String value1, String value2) {
            addCriterion("modelCode not between", value1, value2, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelseriesIsNull() {
            addCriterion("modelSeries is null");
            return (Criteria) this;
        }

        public Criteria andModelseriesIsNotNull() {
            addCriterion("modelSeries is not null");
            return (Criteria) this;
        }

        public Criteria andModelseriesEqualTo(String value) {
            addCriterion("modelSeries =", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesNotEqualTo(String value) {
            addCriterion("modelSeries <>", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesGreaterThan(String value) {
            addCriterion("modelSeries >", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesGreaterThanOrEqualTo(String value) {
            addCriterion("modelSeries >=", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesLessThan(String value) {
            addCriterion("modelSeries <", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesLessThanOrEqualTo(String value) {
            addCriterion("modelSeries <=", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesLike(String value) {
            addCriterion("modelSeries like", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesNotLike(String value) {
            addCriterion("modelSeries not like", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesIn(List<String> values) {
            addCriterion("modelSeries in", values, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesNotIn(List<String> values) {
            addCriterion("modelSeries not in", values, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesBetween(String value1, String value2) {
            addCriterion("modelSeries between", value1, value2, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesNotBetween(String value1, String value2) {
            addCriterion("modelSeries not between", value1, value2, "modelseries");
            return (Criteria) this;
        }

        public Criteria andSeriesIsNull() {
            addCriterion("series is null");
            return (Criteria) this;
        }

        public Criteria andSeriesIsNotNull() {
            addCriterion("series is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesEqualTo(String value) {
            addCriterion("series =", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotEqualTo(String value) {
            addCriterion("series <>", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesGreaterThan(String value) {
            addCriterion("series >", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesGreaterThanOrEqualTo(String value) {
            addCriterion("series >=", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesLessThan(String value) {
            addCriterion("series <", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesLessThanOrEqualTo(String value) {
            addCriterion("series <=", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesLike(String value) {
            addCriterion("series like", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotLike(String value) {
            addCriterion("series not like", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesIn(List<String> values) {
            addCriterion("series in", values, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotIn(List<String> values) {
            addCriterion("series not in", values, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesBetween(String value1, String value2) {
            addCriterion("series between", value1, value2, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotBetween(String value1, String value2) {
            addCriterion("series not between", value1, value2, "series");
            return (Criteria) this;
        }

        public Criteria andColorcodeIsNull() {
            addCriterion("colorCode is null");
            return (Criteria) this;
        }

        public Criteria andColorcodeIsNotNull() {
            addCriterion("colorCode is not null");
            return (Criteria) this;
        }

        public Criteria andColorcodeEqualTo(String value) {
            addCriterion("colorCode =", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeNotEqualTo(String value) {
            addCriterion("colorCode <>", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeGreaterThan(String value) {
            addCriterion("colorCode >", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeGreaterThanOrEqualTo(String value) {
            addCriterion("colorCode >=", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeLessThan(String value) {
            addCriterion("colorCode <", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeLessThanOrEqualTo(String value) {
            addCriterion("colorCode <=", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeLike(String value) {
            addCriterion("colorCode like", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeNotLike(String value) {
            addCriterion("colorCode not like", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeIn(List<String> values) {
            addCriterion("colorCode in", values, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeNotIn(List<String> values) {
            addCriterion("colorCode not in", values, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeBetween(String value1, String value2) {
            addCriterion("colorCode between", value1, value2, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeNotBetween(String value1, String value2) {
            addCriterion("colorCode not between", value1, value2, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColordescIsNull() {
            addCriterion("colorDesc is null");
            return (Criteria) this;
        }

        public Criteria andColordescIsNotNull() {
            addCriterion("colorDesc is not null");
            return (Criteria) this;
        }

        public Criteria andColordescEqualTo(String value) {
            addCriterion("colorDesc =", value, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescNotEqualTo(String value) {
            addCriterion("colorDesc <>", value, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescGreaterThan(String value) {
            addCriterion("colorDesc >", value, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescGreaterThanOrEqualTo(String value) {
            addCriterion("colorDesc >=", value, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescLessThan(String value) {
            addCriterion("colorDesc <", value, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescLessThanOrEqualTo(String value) {
            addCriterion("colorDesc <=", value, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescLike(String value) {
            addCriterion("colorDesc like", value, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescNotLike(String value) {
            addCriterion("colorDesc not like", value, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescIn(List<String> values) {
            addCriterion("colorDesc in", values, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescNotIn(List<String> values) {
            addCriterion("colorDesc not in", values, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescBetween(String value1, String value2) {
            addCriterion("colorDesc between", value1, value2, "colordesc");
            return (Criteria) this;
        }

        public Criteria andColordescNotBetween(String value1, String value2) {
            addCriterion("colorDesc not between", value1, value2, "colordesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeIsNull() {
            addCriterion("upholsteryCode is null");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeIsNotNull() {
            addCriterion("upholsteryCode is not null");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeEqualTo(String value) {
            addCriterion("upholsteryCode =", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeNotEqualTo(String value) {
            addCriterion("upholsteryCode <>", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeGreaterThan(String value) {
            addCriterion("upholsteryCode >", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeGreaterThanOrEqualTo(String value) {
            addCriterion("upholsteryCode >=", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeLessThan(String value) {
            addCriterion("upholsteryCode <", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeLessThanOrEqualTo(String value) {
            addCriterion("upholsteryCode <=", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeLike(String value) {
            addCriterion("upholsteryCode like", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeNotLike(String value) {
            addCriterion("upholsteryCode not like", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeIn(List<String> values) {
            addCriterion("upholsteryCode in", values, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeNotIn(List<String> values) {
            addCriterion("upholsteryCode not in", values, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeBetween(String value1, String value2) {
            addCriterion("upholsteryCode between", value1, value2, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeNotBetween(String value1, String value2) {
            addCriterion("upholsteryCode not between", value1, value2, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescIsNull() {
            addCriterion("upholsteryDesc is null");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescIsNotNull() {
            addCriterion("upholsteryDesc is not null");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescEqualTo(String value) {
            addCriterion("upholsteryDesc =", value, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescNotEqualTo(String value) {
            addCriterion("upholsteryDesc <>", value, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescGreaterThan(String value) {
            addCriterion("upholsteryDesc >", value, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescGreaterThanOrEqualTo(String value) {
            addCriterion("upholsteryDesc >=", value, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescLessThan(String value) {
            addCriterion("upholsteryDesc <", value, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescLessThanOrEqualTo(String value) {
            addCriterion("upholsteryDesc <=", value, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescLike(String value) {
            addCriterion("upholsteryDesc like", value, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescNotLike(String value) {
            addCriterion("upholsteryDesc not like", value, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescIn(List<String> values) {
            addCriterion("upholsteryDesc in", values, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescNotIn(List<String> values) {
            addCriterion("upholsteryDesc not in", values, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescBetween(String value1, String value2) {
            addCriterion("upholsteryDesc between", value1, value2, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andUpholsterydescNotBetween(String value1, String value2) {
            addCriterion("upholsteryDesc not between", value1, value2, "upholsterydesc");
            return (Criteria) this;
        }

        public Criteria andApwIsNull() {
            addCriterion("apw is null");
            return (Criteria) this;
        }

        public Criteria andApwIsNotNull() {
            addCriterion("apw is not null");
            return (Criteria) this;
        }

        public Criteria andApwEqualTo(String value) {
            addCriterion("apw =", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwNotEqualTo(String value) {
            addCriterion("apw <>", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwGreaterThan(String value) {
            addCriterion("apw >", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwGreaterThanOrEqualTo(String value) {
            addCriterion("apw >=", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwLessThan(String value) {
            addCriterion("apw <", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwLessThanOrEqualTo(String value) {
            addCriterion("apw <=", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwLike(String value) {
            addCriterion("apw like", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwNotLike(String value) {
            addCriterion("apw not like", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwIn(List<String> values) {
            addCriterion("apw in", values, "apw");
            return (Criteria) this;
        }

        public Criteria andApwNotIn(List<String> values) {
            addCriterion("apw not in", values, "apw");
            return (Criteria) this;
        }

        public Criteria andApwBetween(String value1, String value2) {
            addCriterion("apw between", value1, value2, "apw");
            return (Criteria) this;
        }

        public Criteria andApwNotBetween(String value1, String value2) {
            addCriterion("apw not between", value1, value2, "apw");
            return (Criteria) this;
        }

        public Criteria andYeartypeIsNull() {
            addCriterion("yeartype is null");
            return (Criteria) this;
        }

        public Criteria andYeartypeIsNotNull() {
            addCriterion("yeartype is not null");
            return (Criteria) this;
        }

        public Criteria andYeartypeEqualTo(String value) {
            addCriterion("yeartype =", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeNotEqualTo(String value) {
            addCriterion("yeartype <>", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeGreaterThan(String value) {
            addCriterion("yeartype >", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeGreaterThanOrEqualTo(String value) {
            addCriterion("yeartype >=", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeLessThan(String value) {
            addCriterion("yeartype <", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeLessThanOrEqualTo(String value) {
            addCriterion("yeartype <=", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeLike(String value) {
            addCriterion("yeartype like", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeNotLike(String value) {
            addCriterion("yeartype not like", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeIn(List<String> values) {
            addCriterion("yeartype in", values, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeNotIn(List<String> values) {
            addCriterion("yeartype not in", values, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeBetween(String value1, String value2) {
            addCriterion("yeartype between", value1, value2, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeNotBetween(String value1, String value2) {
            addCriterion("yeartype not between", value1, value2, "yeartype");
            return (Criteria) this;
        }

        public Criteria andConfigcodeIsNull() {
            addCriterion("configCode is null");
            return (Criteria) this;
        }

        public Criteria andConfigcodeIsNotNull() {
            addCriterion("configCode is not null");
            return (Criteria) this;
        }

        public Criteria andConfigcodeEqualTo(String value) {
            addCriterion("configCode =", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeNotEqualTo(String value) {
            addCriterion("configCode <>", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeGreaterThan(String value) {
            addCriterion("configCode >", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeGreaterThanOrEqualTo(String value) {
            addCriterion("configCode >=", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeLessThan(String value) {
            addCriterion("configCode <", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeLessThanOrEqualTo(String value) {
            addCriterion("configCode <=", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeLike(String value) {
            addCriterion("configCode like", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeNotLike(String value) {
            addCriterion("configCode not like", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeIn(List<String> values) {
            addCriterion("configCode in", values, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeNotIn(List<String> values) {
            addCriterion("configCode not in", values, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeBetween(String value1, String value2) {
            addCriterion("configCode between", value1, value2, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeNotBetween(String value1, String value2) {
            addCriterion("configCode not between", value1, value2, "configcode");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Long value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Long value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Long value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Long value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Long value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Long> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Long> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Long value1, Long value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Long value1, Long value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andAddpriceIsNull() {
            addCriterion("addPrice is null");
            return (Criteria) this;
        }

        public Criteria andAddpriceIsNotNull() {
            addCriterion("addPrice is not null");
            return (Criteria) this;
        }

        public Criteria andAddpriceEqualTo(String value) {
            addCriterion("addPrice =", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceNotEqualTo(String value) {
            addCriterion("addPrice <>", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceGreaterThan(String value) {
            addCriterion("addPrice >", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceGreaterThanOrEqualTo(String value) {
            addCriterion("addPrice >=", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceLessThan(String value) {
            addCriterion("addPrice <", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceLessThanOrEqualTo(String value) {
            addCriterion("addPrice <=", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceLike(String value) {
            addCriterion("addPrice like", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceNotLike(String value) {
            addCriterion("addPrice not like", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceIn(List<String> values) {
            addCriterion("addPrice in", values, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceNotIn(List<String> values) {
            addCriterion("addPrice not in", values, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceBetween(String value1, String value2) {
            addCriterion("addPrice between", value1, value2, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceNotBetween(String value1, String value2) {
            addCriterion("addPrice not between", value1, value2, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddcodeIsNull() {
            addCriterion("addCode is null");
            return (Criteria) this;
        }

        public Criteria andAddcodeIsNotNull() {
            addCriterion("addCode is not null");
            return (Criteria) this;
        }

        public Criteria andAddcodeEqualTo(String value) {
            addCriterion("addCode =", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeNotEqualTo(String value) {
            addCriterion("addCode <>", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeGreaterThan(String value) {
            addCriterion("addCode >", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeGreaterThanOrEqualTo(String value) {
            addCriterion("addCode >=", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeLessThan(String value) {
            addCriterion("addCode <", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeLessThanOrEqualTo(String value) {
            addCriterion("addCode <=", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeLike(String value) {
            addCriterion("addCode like", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeNotLike(String value) {
            addCriterion("addCode not like", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeIn(List<String> values) {
            addCriterion("addCode in", values, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeNotIn(List<String> values) {
            addCriterion("addCode not in", values, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeBetween(String value1, String value2) {
            addCriterion("addCode between", value1, value2, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeNotBetween(String value1, String value2) {
            addCriterion("addCode not between", value1, value2, "addcode");
            return (Criteria) this;
        }

        public Criteria andVariantdescIsNull() {
            addCriterion("variantDesc is null");
            return (Criteria) this;
        }

        public Criteria andVariantdescIsNotNull() {
            addCriterion("variantDesc is not null");
            return (Criteria) this;
        }

        public Criteria andVariantdescEqualTo(String value) {
            addCriterion("variantDesc =", value, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescNotEqualTo(String value) {
            addCriterion("variantDesc <>", value, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescGreaterThan(String value) {
            addCriterion("variantDesc >", value, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescGreaterThanOrEqualTo(String value) {
            addCriterion("variantDesc >=", value, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescLessThan(String value) {
            addCriterion("variantDesc <", value, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescLessThanOrEqualTo(String value) {
            addCriterion("variantDesc <=", value, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescLike(String value) {
            addCriterion("variantDesc like", value, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescNotLike(String value) {
            addCriterion("variantDesc not like", value, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescIn(List<String> values) {
            addCriterion("variantDesc in", values, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescNotIn(List<String> values) {
            addCriterion("variantDesc not in", values, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescBetween(String value1, String value2) {
            addCriterion("variantDesc between", value1, value2, "variantdesc");
            return (Criteria) this;
        }

        public Criteria andVariantdescNotBetween(String value1, String value2) {
            addCriterion("variantDesc not between", value1, value2, "variantdesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales.materials
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 16 14:59:27 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales.materials
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}