package com.bmw.entity;

public class Materials {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.materialsId
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String materialsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.carType
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String cartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.modelCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String modelcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.modelSeries
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String modelseries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.series
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String series;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.colorCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String colorcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.colorDesc
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String colordesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.upholsteryCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String upholsterycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.upholsteryDesc
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String upholsterydesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.apw
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String apw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.yeartype
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String yeartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.configCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String configcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.price
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.addPrice
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String addprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.addCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String addcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.materials.variantDesc
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    private String variantdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.materialsId
     *
     * @return the value of sales.materials.materialsId
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getMaterialsid() {
        return materialsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.materialsId
     *
     * @param materialsid the value for sales.materials.materialsId
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setMaterialsid(String materialsid) {
        this.materialsid = materialsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.carType
     *
     * @return the value of sales.materials.carType
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.carType
     *
     * @param cartype the value for sales.materials.carType
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setCartype(String cartype) {
        this.cartype = cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.modelCode
     *
     * @return the value of sales.materials.modelCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getModelcode() {
        return modelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.modelCode
     *
     * @param modelcode the value for sales.materials.modelCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setModelcode(String modelcode) {
        this.modelcode = modelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.modelSeries
     *
     * @return the value of sales.materials.modelSeries
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getModelseries() {
        return modelseries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.modelSeries
     *
     * @param modelseries the value for sales.materials.modelSeries
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setModelseries(String modelseries) {
        this.modelseries = modelseries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.series
     *
     * @return the value of sales.materials.series
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.series
     *
     * @param series the value for sales.materials.series
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setSeries(String series) {
        this.series = series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.colorCode
     *
     * @return the value of sales.materials.colorCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getColorcode() {
        return colorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.colorCode
     *
     * @param colorcode the value for sales.materials.colorCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setColorcode(String colorcode) {
        this.colorcode = colorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.colorDesc
     *
     * @return the value of sales.materials.colorDesc
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getColordesc() {
        return colordesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.colorDesc
     *
     * @param colordesc the value for sales.materials.colorDesc
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setColordesc(String colordesc) {
        this.colordesc = colordesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.upholsteryCode
     *
     * @return the value of sales.materials.upholsteryCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getUpholsterycode() {
        return upholsterycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.upholsteryCode
     *
     * @param upholsterycode the value for sales.materials.upholsteryCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setUpholsterycode(String upholsterycode) {
        this.upholsterycode = upholsterycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.upholsteryDesc
     *
     * @return the value of sales.materials.upholsteryDesc
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getUpholsterydesc() {
        return upholsterydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.upholsteryDesc
     *
     * @param upholsterydesc the value for sales.materials.upholsteryDesc
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setUpholsterydesc(String upholsterydesc) {
        this.upholsterydesc = upholsterydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.apw
     *
     * @return the value of sales.materials.apw
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getApw() {
        return apw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.apw
     *
     * @param apw the value for sales.materials.apw
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setApw(String apw) {
        this.apw = apw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.yeartype
     *
     * @return the value of sales.materials.yeartype
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getYeartype() {
        return yeartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.yeartype
     *
     * @param yeartype the value for sales.materials.yeartype
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setYeartype(String yeartype) {
        this.yeartype = yeartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.configCode
     *
     * @return the value of sales.materials.configCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getConfigcode() {
        return configcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.configCode
     *
     * @param configcode the value for sales.materials.configCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setConfigcode(String configcode) {
        this.configcode = configcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.price
     *
     * @return the value of sales.materials.price
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.price
     *
     * @param price the value for sales.materials.price
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.addPrice
     *
     * @return the value of sales.materials.addPrice
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getAddprice() {
        return addprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.addPrice
     *
     * @param addprice the value for sales.materials.addPrice
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setAddprice(String addprice) {
        this.addprice = addprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.addCode
     *
     * @return the value of sales.materials.addCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getAddcode() {
        return addcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.addCode
     *
     * @param addcode the value for sales.materials.addCode
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setAddcode(String addcode) {
        this.addcode = addcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.materials.variantDesc
     *
     * @return the value of sales.materials.variantDesc
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public String getVariantdesc() {
        return variantdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.materials.variantDesc
     *
     * @param variantdesc the value for sales.materials.variantDesc
     *
     * @mbg.generated Fri Aug 16 14:59:27 CST 2019
     */
    public void setVariantdesc(String variantdesc) {
        this.variantdesc = variantdesc;
    }
}