package com.bmw.entity;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.id
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.orderId
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.carType
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String cartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.modelCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String modelcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.modelDesc
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String modeldesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.modelSeries
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String modelseries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.colorCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String colorcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.upholsteryCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String upholsterycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.apw
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String apw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.yearType
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String yeartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.configCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String configcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.price
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.addPrice
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String addprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.addCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String addcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.dealerId
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String dealerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.dealerStatus
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String dealerstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.colorFav
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private Long colorfav;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.upholsteryFav
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private Long upholsteryfav;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.modelFav
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private Long modelfav;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.order.materialsId
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    private String materialsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.id
     *
     * @return the value of sales.order.id
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.id
     *
     * @param id the value for sales.order.id
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.orderId
     *
     * @return the value of sales.order.orderId
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.orderId
     *
     * @param orderid the value for sales.order.orderId
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.carType
     *
     * @return the value of sales.order.carType
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.carType
     *
     * @param cartype the value for sales.order.carType
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setCartype(String cartype) {
        this.cartype = cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.modelCode
     *
     * @return the value of sales.order.modelCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getModelcode() {
        return modelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.modelCode
     *
     * @param modelcode the value for sales.order.modelCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setModelcode(String modelcode) {
        this.modelcode = modelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.modelDesc
     *
     * @return the value of sales.order.modelDesc
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getModeldesc() {
        return modeldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.modelDesc
     *
     * @param modeldesc the value for sales.order.modelDesc
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setModeldesc(String modeldesc) {
        this.modeldesc = modeldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.modelSeries
     *
     * @return the value of sales.order.modelSeries
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getModelseries() {
        return modelseries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.modelSeries
     *
     * @param modelseries the value for sales.order.modelSeries
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setModelseries(String modelseries) {
        this.modelseries = modelseries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.colorCode
     *
     * @return the value of sales.order.colorCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getColorcode() {
        return colorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.colorCode
     *
     * @param colorcode the value for sales.order.colorCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setColorcode(String colorcode) {
        this.colorcode = colorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.upholsteryCode
     *
     * @return the value of sales.order.upholsteryCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getUpholsterycode() {
        return upholsterycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.upholsteryCode
     *
     * @param upholsterycode the value for sales.order.upholsteryCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setUpholsterycode(String upholsterycode) {
        this.upholsterycode = upholsterycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.apw
     *
     * @return the value of sales.order.apw
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getApw() {
        return apw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.apw
     *
     * @param apw the value for sales.order.apw
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setApw(String apw) {
        this.apw = apw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.yearType
     *
     * @return the value of sales.order.yearType
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getYeartype() {
        return yeartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.yearType
     *
     * @param yeartype the value for sales.order.yearType
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setYeartype(String yeartype) {
        this.yeartype = yeartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.configCode
     *
     * @return the value of sales.order.configCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getConfigcode() {
        return configcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.configCode
     *
     * @param configcode the value for sales.order.configCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setConfigcode(String configcode) {
        this.configcode = configcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.price
     *
     * @return the value of sales.order.price
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.price
     *
     * @param price the value for sales.order.price
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.addPrice
     *
     * @return the value of sales.order.addPrice
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getAddprice() {
        return addprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.addPrice
     *
     * @param addprice the value for sales.order.addPrice
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setAddprice(String addprice) {
        this.addprice = addprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.addCode
     *
     * @return the value of sales.order.addCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getAddcode() {
        return addcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.addCode
     *
     * @param addcode the value for sales.order.addCode
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setAddcode(String addcode) {
        this.addcode = addcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.dealerId
     *
     * @return the value of sales.order.dealerId
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getDealerid() {
        return dealerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.dealerId
     *
     * @param dealerid the value for sales.order.dealerId
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setDealerid(String dealerid) {
        this.dealerid = dealerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.dealerStatus
     *
     * @return the value of sales.order.dealerStatus
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getDealerstatus() {
        return dealerstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.dealerStatus
     *
     * @param dealerstatus the value for sales.order.dealerStatus
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setDealerstatus(String dealerstatus) {
        this.dealerstatus = dealerstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.colorFav
     *
     * @return the value of sales.order.colorFav
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public Long getColorfav() {
        return colorfav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.colorFav
     *
     * @param colorfav the value for sales.order.colorFav
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setColorfav(Long colorfav) {
        this.colorfav = colorfav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.upholsteryFav
     *
     * @return the value of sales.order.upholsteryFav
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public Long getUpholsteryfav() {
        return upholsteryfav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.upholsteryFav
     *
     * @param upholsteryfav the value for sales.order.upholsteryFav
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setUpholsteryfav(Long upholsteryfav) {
        this.upholsteryfav = upholsteryfav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.modelFav
     *
     * @return the value of sales.order.modelFav
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public Long getModelfav() {
        return modelfav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.modelFav
     *
     * @param modelfav the value for sales.order.modelFav
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setModelfav(Long modelfav) {
        this.modelfav = modelfav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.order.materialsId
     *
     * @return the value of sales.order.materialsId
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getMaterialsid() {
        return materialsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.order.materialsId
     *
     * @param materialsid the value for sales.order.materialsId
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setMaterialsid(String materialsid) {
        this.materialsid = materialsid;
    }
}