package com.bmw.entity;

import java.util.ArrayList;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderId is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("orderId =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("orderId <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("orderId >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("orderId >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("orderId <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("orderId <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("orderId like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("orderId not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("orderId in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("orderId not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("orderId between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("orderId not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andCartypeIsNull() {
            addCriterion("carType is null");
            return (Criteria) this;
        }

        public Criteria andCartypeIsNotNull() {
            addCriterion("carType is not null");
            return (Criteria) this;
        }

        public Criteria andCartypeEqualTo(String value) {
            addCriterion("carType =", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotEqualTo(String value) {
            addCriterion("carType <>", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeGreaterThan(String value) {
            addCriterion("carType >", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeGreaterThanOrEqualTo(String value) {
            addCriterion("carType >=", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLessThan(String value) {
            addCriterion("carType <", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLessThanOrEqualTo(String value) {
            addCriterion("carType <=", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLike(String value) {
            addCriterion("carType like", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotLike(String value) {
            addCriterion("carType not like", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeIn(List<String> values) {
            addCriterion("carType in", values, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotIn(List<String> values) {
            addCriterion("carType not in", values, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeBetween(String value1, String value2) {
            addCriterion("carType between", value1, value2, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotBetween(String value1, String value2) {
            addCriterion("carType not between", value1, value2, "cartype");
            return (Criteria) this;
        }

        public Criteria andModelcodeIsNull() {
            addCriterion("modelCode is null");
            return (Criteria) this;
        }

        public Criteria andModelcodeIsNotNull() {
            addCriterion("modelCode is not null");
            return (Criteria) this;
        }

        public Criteria andModelcodeEqualTo(String value) {
            addCriterion("modelCode =", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeNotEqualTo(String value) {
            addCriterion("modelCode <>", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeGreaterThan(String value) {
            addCriterion("modelCode >", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeGreaterThanOrEqualTo(String value) {
            addCriterion("modelCode >=", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeLessThan(String value) {
            addCriterion("modelCode <", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeLessThanOrEqualTo(String value) {
            addCriterion("modelCode <=", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeLike(String value) {
            addCriterion("modelCode like", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeNotLike(String value) {
            addCriterion("modelCode not like", value, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeIn(List<String> values) {
            addCriterion("modelCode in", values, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeNotIn(List<String> values) {
            addCriterion("modelCode not in", values, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeBetween(String value1, String value2) {
            addCriterion("modelCode between", value1, value2, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModelcodeNotBetween(String value1, String value2) {
            addCriterion("modelCode not between", value1, value2, "modelcode");
            return (Criteria) this;
        }

        public Criteria andModeldescIsNull() {
            addCriterion("modelDesc is null");
            return (Criteria) this;
        }

        public Criteria andModeldescIsNotNull() {
            addCriterion("modelDesc is not null");
            return (Criteria) this;
        }

        public Criteria andModeldescEqualTo(String value) {
            addCriterion("modelDesc =", value, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescNotEqualTo(String value) {
            addCriterion("modelDesc <>", value, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescGreaterThan(String value) {
            addCriterion("modelDesc >", value, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescGreaterThanOrEqualTo(String value) {
            addCriterion("modelDesc >=", value, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescLessThan(String value) {
            addCriterion("modelDesc <", value, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescLessThanOrEqualTo(String value) {
            addCriterion("modelDesc <=", value, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescLike(String value) {
            addCriterion("modelDesc like", value, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescNotLike(String value) {
            addCriterion("modelDesc not like", value, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescIn(List<String> values) {
            addCriterion("modelDesc in", values, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescNotIn(List<String> values) {
            addCriterion("modelDesc not in", values, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescBetween(String value1, String value2) {
            addCriterion("modelDesc between", value1, value2, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModeldescNotBetween(String value1, String value2) {
            addCriterion("modelDesc not between", value1, value2, "modeldesc");
            return (Criteria) this;
        }

        public Criteria andModelseriesIsNull() {
            addCriterion("modelSeries is null");
            return (Criteria) this;
        }

        public Criteria andModelseriesIsNotNull() {
            addCriterion("modelSeries is not null");
            return (Criteria) this;
        }

        public Criteria andModelseriesEqualTo(String value) {
            addCriterion("modelSeries =", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesNotEqualTo(String value) {
            addCriterion("modelSeries <>", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesGreaterThan(String value) {
            addCriterion("modelSeries >", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesGreaterThanOrEqualTo(String value) {
            addCriterion("modelSeries >=", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesLessThan(String value) {
            addCriterion("modelSeries <", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesLessThanOrEqualTo(String value) {
            addCriterion("modelSeries <=", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesLike(String value) {
            addCriterion("modelSeries like", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesNotLike(String value) {
            addCriterion("modelSeries not like", value, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesIn(List<String> values) {
            addCriterion("modelSeries in", values, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesNotIn(List<String> values) {
            addCriterion("modelSeries not in", values, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesBetween(String value1, String value2) {
            addCriterion("modelSeries between", value1, value2, "modelseries");
            return (Criteria) this;
        }

        public Criteria andModelseriesNotBetween(String value1, String value2) {
            addCriterion("modelSeries not between", value1, value2, "modelseries");
            return (Criteria) this;
        }

        public Criteria andColorcodeIsNull() {
            addCriterion("colorCode is null");
            return (Criteria) this;
        }

        public Criteria andColorcodeIsNotNull() {
            addCriterion("colorCode is not null");
            return (Criteria) this;
        }

        public Criteria andColorcodeEqualTo(String value) {
            addCriterion("colorCode =", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeNotEqualTo(String value) {
            addCriterion("colorCode <>", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeGreaterThan(String value) {
            addCriterion("colorCode >", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeGreaterThanOrEqualTo(String value) {
            addCriterion("colorCode >=", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeLessThan(String value) {
            addCriterion("colorCode <", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeLessThanOrEqualTo(String value) {
            addCriterion("colorCode <=", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeLike(String value) {
            addCriterion("colorCode like", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeNotLike(String value) {
            addCriterion("colorCode not like", value, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeIn(List<String> values) {
            addCriterion("colorCode in", values, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeNotIn(List<String> values) {
            addCriterion("colorCode not in", values, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeBetween(String value1, String value2) {
            addCriterion("colorCode between", value1, value2, "colorcode");
            return (Criteria) this;
        }

        public Criteria andColorcodeNotBetween(String value1, String value2) {
            addCriterion("colorCode not between", value1, value2, "colorcode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeIsNull() {
            addCriterion("upholsteryCode is null");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeIsNotNull() {
            addCriterion("upholsteryCode is not null");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeEqualTo(String value) {
            addCriterion("upholsteryCode =", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeNotEqualTo(String value) {
            addCriterion("upholsteryCode <>", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeGreaterThan(String value) {
            addCriterion("upholsteryCode >", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeGreaterThanOrEqualTo(String value) {
            addCriterion("upholsteryCode >=", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeLessThan(String value) {
            addCriterion("upholsteryCode <", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeLessThanOrEqualTo(String value) {
            addCriterion("upholsteryCode <=", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeLike(String value) {
            addCriterion("upholsteryCode like", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeNotLike(String value) {
            addCriterion("upholsteryCode not like", value, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeIn(List<String> values) {
            addCriterion("upholsteryCode in", values, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeNotIn(List<String> values) {
            addCriterion("upholsteryCode not in", values, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeBetween(String value1, String value2) {
            addCriterion("upholsteryCode between", value1, value2, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andUpholsterycodeNotBetween(String value1, String value2) {
            addCriterion("upholsteryCode not between", value1, value2, "upholsterycode");
            return (Criteria) this;
        }

        public Criteria andApwIsNull() {
            addCriterion("apw is null");
            return (Criteria) this;
        }

        public Criteria andApwIsNotNull() {
            addCriterion("apw is not null");
            return (Criteria) this;
        }

        public Criteria andApwEqualTo(String value) {
            addCriterion("apw =", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwNotEqualTo(String value) {
            addCriterion("apw <>", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwGreaterThan(String value) {
            addCriterion("apw >", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwGreaterThanOrEqualTo(String value) {
            addCriterion("apw >=", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwLessThan(String value) {
            addCriterion("apw <", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwLessThanOrEqualTo(String value) {
            addCriterion("apw <=", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwLike(String value) {
            addCriterion("apw like", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwNotLike(String value) {
            addCriterion("apw not like", value, "apw");
            return (Criteria) this;
        }

        public Criteria andApwIn(List<String> values) {
            addCriterion("apw in", values, "apw");
            return (Criteria) this;
        }

        public Criteria andApwNotIn(List<String> values) {
            addCriterion("apw not in", values, "apw");
            return (Criteria) this;
        }

        public Criteria andApwBetween(String value1, String value2) {
            addCriterion("apw between", value1, value2, "apw");
            return (Criteria) this;
        }

        public Criteria andApwNotBetween(String value1, String value2) {
            addCriterion("apw not between", value1, value2, "apw");
            return (Criteria) this;
        }

        public Criteria andYeartypeIsNull() {
            addCriterion("yearType is null");
            return (Criteria) this;
        }

        public Criteria andYeartypeIsNotNull() {
            addCriterion("yearType is not null");
            return (Criteria) this;
        }

        public Criteria andYeartypeEqualTo(String value) {
            addCriterion("yearType =", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeNotEqualTo(String value) {
            addCriterion("yearType <>", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeGreaterThan(String value) {
            addCriterion("yearType >", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeGreaterThanOrEqualTo(String value) {
            addCriterion("yearType >=", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeLessThan(String value) {
            addCriterion("yearType <", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeLessThanOrEqualTo(String value) {
            addCriterion("yearType <=", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeLike(String value) {
            addCriterion("yearType like", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeNotLike(String value) {
            addCriterion("yearType not like", value, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeIn(List<String> values) {
            addCriterion("yearType in", values, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeNotIn(List<String> values) {
            addCriterion("yearType not in", values, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeBetween(String value1, String value2) {
            addCriterion("yearType between", value1, value2, "yeartype");
            return (Criteria) this;
        }

        public Criteria andYeartypeNotBetween(String value1, String value2) {
            addCriterion("yearType not between", value1, value2, "yeartype");
            return (Criteria) this;
        }

        public Criteria andConfigcodeIsNull() {
            addCriterion("configCode is null");
            return (Criteria) this;
        }

        public Criteria andConfigcodeIsNotNull() {
            addCriterion("configCode is not null");
            return (Criteria) this;
        }

        public Criteria andConfigcodeEqualTo(String value) {
            addCriterion("configCode =", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeNotEqualTo(String value) {
            addCriterion("configCode <>", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeGreaterThan(String value) {
            addCriterion("configCode >", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeGreaterThanOrEqualTo(String value) {
            addCriterion("configCode >=", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeLessThan(String value) {
            addCriterion("configCode <", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeLessThanOrEqualTo(String value) {
            addCriterion("configCode <=", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeLike(String value) {
            addCriterion("configCode like", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeNotLike(String value) {
            addCriterion("configCode not like", value, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeIn(List<String> values) {
            addCriterion("configCode in", values, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeNotIn(List<String> values) {
            addCriterion("configCode not in", values, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeBetween(String value1, String value2) {
            addCriterion("configCode between", value1, value2, "configcode");
            return (Criteria) this;
        }

        public Criteria andConfigcodeNotBetween(String value1, String value2) {
            addCriterion("configCode not between", value1, value2, "configcode");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Long value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Long value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Long value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Long value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Long value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Long> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Long> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Long value1, Long value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Long value1, Long value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andAddpriceIsNull() {
            addCriterion("addPrice is null");
            return (Criteria) this;
        }

        public Criteria andAddpriceIsNotNull() {
            addCriterion("addPrice is not null");
            return (Criteria) this;
        }

        public Criteria andAddpriceEqualTo(String value) {
            addCriterion("addPrice =", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceNotEqualTo(String value) {
            addCriterion("addPrice <>", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceGreaterThan(String value) {
            addCriterion("addPrice >", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceGreaterThanOrEqualTo(String value) {
            addCriterion("addPrice >=", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceLessThan(String value) {
            addCriterion("addPrice <", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceLessThanOrEqualTo(String value) {
            addCriterion("addPrice <=", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceLike(String value) {
            addCriterion("addPrice like", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceNotLike(String value) {
            addCriterion("addPrice not like", value, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceIn(List<String> values) {
            addCriterion("addPrice in", values, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceNotIn(List<String> values) {
            addCriterion("addPrice not in", values, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceBetween(String value1, String value2) {
            addCriterion("addPrice between", value1, value2, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddpriceNotBetween(String value1, String value2) {
            addCriterion("addPrice not between", value1, value2, "addprice");
            return (Criteria) this;
        }

        public Criteria andAddcodeIsNull() {
            addCriterion("addCode is null");
            return (Criteria) this;
        }

        public Criteria andAddcodeIsNotNull() {
            addCriterion("addCode is not null");
            return (Criteria) this;
        }

        public Criteria andAddcodeEqualTo(String value) {
            addCriterion("addCode =", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeNotEqualTo(String value) {
            addCriterion("addCode <>", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeGreaterThan(String value) {
            addCriterion("addCode >", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeGreaterThanOrEqualTo(String value) {
            addCriterion("addCode >=", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeLessThan(String value) {
            addCriterion("addCode <", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeLessThanOrEqualTo(String value) {
            addCriterion("addCode <=", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeLike(String value) {
            addCriterion("addCode like", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeNotLike(String value) {
            addCriterion("addCode not like", value, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeIn(List<String> values) {
            addCriterion("addCode in", values, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeNotIn(List<String> values) {
            addCriterion("addCode not in", values, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeBetween(String value1, String value2) {
            addCriterion("addCode between", value1, value2, "addcode");
            return (Criteria) this;
        }

        public Criteria andAddcodeNotBetween(String value1, String value2) {
            addCriterion("addCode not between", value1, value2, "addcode");
            return (Criteria) this;
        }

        public Criteria andDealeridIsNull() {
            addCriterion("dealerId is null");
            return (Criteria) this;
        }

        public Criteria andDealeridIsNotNull() {
            addCriterion("dealerId is not null");
            return (Criteria) this;
        }

        public Criteria andDealeridEqualTo(String value) {
            addCriterion("dealerId =", value, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridNotEqualTo(String value) {
            addCriterion("dealerId <>", value, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridGreaterThan(String value) {
            addCriterion("dealerId >", value, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridGreaterThanOrEqualTo(String value) {
            addCriterion("dealerId >=", value, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridLessThan(String value) {
            addCriterion("dealerId <", value, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridLessThanOrEqualTo(String value) {
            addCriterion("dealerId <=", value, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridLike(String value) {
            addCriterion("dealerId like", value, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridNotLike(String value) {
            addCriterion("dealerId not like", value, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridIn(List<String> values) {
            addCriterion("dealerId in", values, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridNotIn(List<String> values) {
            addCriterion("dealerId not in", values, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridBetween(String value1, String value2) {
            addCriterion("dealerId between", value1, value2, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealeridNotBetween(String value1, String value2) {
            addCriterion("dealerId not between", value1, value2, "dealerid");
            return (Criteria) this;
        }

        public Criteria andDealerstatusIsNull() {
            addCriterion("dealerStatus is null");
            return (Criteria) this;
        }

        public Criteria andDealerstatusIsNotNull() {
            addCriterion("dealerStatus is not null");
            return (Criteria) this;
        }

        public Criteria andDealerstatusEqualTo(String value) {
            addCriterion("dealerStatus =", value, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusNotEqualTo(String value) {
            addCriterion("dealerStatus <>", value, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusGreaterThan(String value) {
            addCriterion("dealerStatus >", value, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusGreaterThanOrEqualTo(String value) {
            addCriterion("dealerStatus >=", value, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusLessThan(String value) {
            addCriterion("dealerStatus <", value, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusLessThanOrEqualTo(String value) {
            addCriterion("dealerStatus <=", value, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusLike(String value) {
            addCriterion("dealerStatus like", value, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusNotLike(String value) {
            addCriterion("dealerStatus not like", value, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusIn(List<String> values) {
            addCriterion("dealerStatus in", values, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusNotIn(List<String> values) {
            addCriterion("dealerStatus not in", values, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusBetween(String value1, String value2) {
            addCriterion("dealerStatus between", value1, value2, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andDealerstatusNotBetween(String value1, String value2) {
            addCriterion("dealerStatus not between", value1, value2, "dealerstatus");
            return (Criteria) this;
        }

        public Criteria andColorfavIsNull() {
            addCriterion("colorFav is null");
            return (Criteria) this;
        }

        public Criteria andColorfavIsNotNull() {
            addCriterion("colorFav is not null");
            return (Criteria) this;
        }

        public Criteria andColorfavEqualTo(Long value) {
            addCriterion("colorFav =", value, "colorfav");
            return (Criteria) this;
        }

        public Criteria andColorfavNotEqualTo(Long value) {
            addCriterion("colorFav <>", value, "colorfav");
            return (Criteria) this;
        }

        public Criteria andColorfavGreaterThan(Long value) {
            addCriterion("colorFav >", value, "colorfav");
            return (Criteria) this;
        }

        public Criteria andColorfavGreaterThanOrEqualTo(Long value) {
            addCriterion("colorFav >=", value, "colorfav");
            return (Criteria) this;
        }

        public Criteria andColorfavLessThan(Long value) {
            addCriterion("colorFav <", value, "colorfav");
            return (Criteria) this;
        }

        public Criteria andColorfavLessThanOrEqualTo(Long value) {
            addCriterion("colorFav <=", value, "colorfav");
            return (Criteria) this;
        }

        public Criteria andColorfavIn(List<Long> values) {
            addCriterion("colorFav in", values, "colorfav");
            return (Criteria) this;
        }

        public Criteria andColorfavNotIn(List<Long> values) {
            addCriterion("colorFav not in", values, "colorfav");
            return (Criteria) this;
        }

        public Criteria andColorfavBetween(Long value1, Long value2) {
            addCriterion("colorFav between", value1, value2, "colorfav");
            return (Criteria) this;
        }

        public Criteria andColorfavNotBetween(Long value1, Long value2) {
            addCriterion("colorFav not between", value1, value2, "colorfav");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavIsNull() {
            addCriterion("upholsteryFav is null");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavIsNotNull() {
            addCriterion("upholsteryFav is not null");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavEqualTo(Long value) {
            addCriterion("upholsteryFav =", value, "upholsteryfav");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavNotEqualTo(Long value) {
            addCriterion("upholsteryFav <>", value, "upholsteryfav");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavGreaterThan(Long value) {
            addCriterion("upholsteryFav >", value, "upholsteryfav");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavGreaterThanOrEqualTo(Long value) {
            addCriterion("upholsteryFav >=", value, "upholsteryfav");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavLessThan(Long value) {
            addCriterion("upholsteryFav <", value, "upholsteryfav");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavLessThanOrEqualTo(Long value) {
            addCriterion("upholsteryFav <=", value, "upholsteryfav");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavIn(List<Long> values) {
            addCriterion("upholsteryFav in", values, "upholsteryfav");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavNotIn(List<Long> values) {
            addCriterion("upholsteryFav not in", values, "upholsteryfav");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavBetween(Long value1, Long value2) {
            addCriterion("upholsteryFav between", value1, value2, "upholsteryfav");
            return (Criteria) this;
        }

        public Criteria andUpholsteryfavNotBetween(Long value1, Long value2) {
            addCriterion("upholsteryFav not between", value1, value2, "upholsteryfav");
            return (Criteria) this;
        }

        public Criteria andModelfavIsNull() {
            addCriterion("modelFav is null");
            return (Criteria) this;
        }

        public Criteria andModelfavIsNotNull() {
            addCriterion("modelFav is not null");
            return (Criteria) this;
        }

        public Criteria andModelfavEqualTo(Long value) {
            addCriterion("modelFav =", value, "modelfav");
            return (Criteria) this;
        }

        public Criteria andModelfavNotEqualTo(Long value) {
            addCriterion("modelFav <>", value, "modelfav");
            return (Criteria) this;
        }

        public Criteria andModelfavGreaterThan(Long value) {
            addCriterion("modelFav >", value, "modelfav");
            return (Criteria) this;
        }

        public Criteria andModelfavGreaterThanOrEqualTo(Long value) {
            addCriterion("modelFav >=", value, "modelfav");
            return (Criteria) this;
        }

        public Criteria andModelfavLessThan(Long value) {
            addCriterion("modelFav <", value, "modelfav");
            return (Criteria) this;
        }

        public Criteria andModelfavLessThanOrEqualTo(Long value) {
            addCriterion("modelFav <=", value, "modelfav");
            return (Criteria) this;
        }

        public Criteria andModelfavIn(List<Long> values) {
            addCriterion("modelFav in", values, "modelfav");
            return (Criteria) this;
        }

        public Criteria andModelfavNotIn(List<Long> values) {
            addCriterion("modelFav not in", values, "modelfav");
            return (Criteria) this;
        }

        public Criteria andModelfavBetween(Long value1, Long value2) {
            addCriterion("modelFav between", value1, value2, "modelfav");
            return (Criteria) this;
        }

        public Criteria andModelfavNotBetween(Long value1, Long value2) {
            addCriterion("modelFav not between", value1, value2, "modelfav");
            return (Criteria) this;
        }

        public Criteria andMaterialsidIsNull() {
            addCriterion("materialsId is null");
            return (Criteria) this;
        }

        public Criteria andMaterialsidIsNotNull() {
            addCriterion("materialsId is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialsidEqualTo(String value) {
            addCriterion("materialsId =", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidNotEqualTo(String value) {
            addCriterion("materialsId <>", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidGreaterThan(String value) {
            addCriterion("materialsId >", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidGreaterThanOrEqualTo(String value) {
            addCriterion("materialsId >=", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidLessThan(String value) {
            addCriterion("materialsId <", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidLessThanOrEqualTo(String value) {
            addCriterion("materialsId <=", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidLike(String value) {
            addCriterion("materialsId like", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidNotLike(String value) {
            addCriterion("materialsId not like", value, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidIn(List<String> values) {
            addCriterion("materialsId in", values, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidNotIn(List<String> values) {
            addCriterion("materialsId not in", values, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidBetween(String value1, String value2) {
            addCriterion("materialsId between", value1, value2, "materialsid");
            return (Criteria) this;
        }

        public Criteria andMaterialsidNotBetween(String value1, String value2) {
            addCriterion("materialsId not between", value1, value2, "materialsid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales.order
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 16 22:01:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales.order
     *
     * @mbg.generated Fri Aug 16 22:01:36 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}